name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: "Install dependencies"
        run: yarn install --frozen-lockfile
      - name: "Build"
        run: yarn build
      - name: "Zip build"
        run: zip -r simple-translate-extension-chrome-mv3-prod.zip build/chrome-mv3-prod
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: simple-translate-extension-chrome-mv3-prod.zip
          generate_release_notes: true
